### ISSUE TITLE
Mention "extern void"

### ISSUE THREAD

**Issue by pmor13** [jeremy-rifkin/c-cpp-trivia#2]
This C code is valid:
```
extern void x;

void f1(void);
void f(int i)
{
    i ? f1() : x;
}

extern const void x1;
const void* p = &x1;
```

Extra: `typedef` need not go first:
```
int typedef T;
```

**Comment by jeremy-rifkin** [comment]
Excellent! I'll add them when I get the chance. I see `extern void x;` is accepted by GCC and Clang but not MSVC (tested wth `cl /TC /std:c11 /permissive-`). I'll hunt for a standard quote on this!

**Comment by pmor13** [comment]
Demo of the ((un)fortunately?) very lax rules of C:
 ```
signed _Noreturn const long volatile long static _Atomic int inline f(void);
 ```

**Comment by jeremy-rifkin** [comment]
I've added these, thanks so much!

**Comment by pmor13** [comment]
Extra: about `void v;` (i.e. w/o `extern`): see https://github.com/llvm/llvm-project/issues/53613.

**Comment by jeremy-rifkin** [comment]
Hmm interesting, thanks for sharing :) I'll leave off for now since the diagnostic isn't misleading, but cool nonetheless!
